update submodule blackbox-tests (zsh3, mksh bugfix)
M: blackbox-tests:
  * git submodule updated:
     - now the testsuote works correcly even with mirbsd korn shell
       (added a workaround for a bug in the combo "mksh"+"glibc")
     - now "distcheck" works ok even when `CONFIG_SHELL' is zsh3

M: Makefile.am:
  * added proper `distclean-local' to remove files errenously left behind
    by Zsh 3.x, so to avoid spurious `distcheck' failures

M: configure.ac:
  * added checks for `$FGREP', used in new `distclean-local' target in
    Makefile.am

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -27,4 +27,37 @@ dist_doc_DATA = README BUGS NEWS
 # This is defined here so that it can be extended in maint/*.mk, if needed.
 distcheck-hook:
 
+# If config.status or configure are run by Zsh 3.x, they can erroneously
+# leave behind some temporary files, and this causes "make distcheck" to
+# fail.  So we clean up those temporary files by hand if ${SHELL} is
+# determined to be Zsh 3.x
+distclean-local:
+	@case `$(SHELL) -c 'echo "$$ZSH_VERSION"'` in \
+	   3.*) ;; \
+	     *) exit 0;; \
+	 esac; \
+	 e=0; \
+	 xrun() { echo " $$*"; "$$@" || { e=1; return 1; } }; \
+	 for subdir in 'blackbox-tests' '.'; do \
+	   ocwd=`pwd`; \
+	   xrun cd "$$subdir" || continue; \
+	   xrun rm -f conftest*; \
+	   xrun rm -f confdefs.h; \
+	   : temporary directories left by config.status are tricky to find; \
+	   for d in conf*; do \
+	     if test -f "$$d/subs.awk" \
+	         && $(FGREP) "PACKAGE_NAME" "$$d/subs.awk" >/dev/null \
+	         && $(FGREP) '$(PACKAGE_NAME)' "$$d/subs.awk" >/dev/null; \
+	     then \
+	       xrun rm -f "$$d"/*; \
+	       xrun rmdir "$$d"; \
+	     fi; \
+	   done; \
+	   xrun cd "$$ocwd" || { \
+	     echo "$@: FATAL: cannot chdir back to \`$$ocwd'" >&2;  \
+		 exit 1; \
+	   }; \
+	 done; \
+	 exit $$e
+
 ## vim: ft=automake noet sw=4 ts=4
