ChangeLog generated in dist-hook
* Makefile.am (dist-hook-generate-changelog): New target, creates
a ChangeLog file in the $(distdir), from git commit messages.
(dist-hook): Depends on it.
(changelog_start_date, FORCE_CHANGELOG_GENERATION): New variables,
used by the new just-described target.
(EXTRA_DIST): Removed ChangeLog.
* maint/git-generate-changelog.mk: Deleted ...
* maint/prj-post-cfg.mk: ... and removed its inclusion in this file.
(changelog-start-date): Definition removed, no more needed.
* .gitignore: Removed ChangeLog.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -14,7 +14,6 @@ dist_doc_DATA = README BUGS NEWS
 EXTRA_DIST = \
   xfail-tests.list \
   HACKING \
-  ChangeLog \
   ChangeLog-old \
   build-aux/gitlog-to-changelog \
   build-aux/git-version-gen \
@@ -27,6 +26,15 @@ EXTRA_DIST = \
 
 # List of files which must not be put in the distributed tarball.
 no_dist_files = maint/config.site maint/local-cfg.mk maint/personal/*
+
+# Enabling of maintainer rules.
+if ENABLE_MAINTAINER_MAKE_RULES
+  ENABLE_MAINTAINER_MAKE_RULES = yes ## used by maint.mk
+  FORCE_CHANGELOG_GENERATION = yes
+else
+  ENABLE_MAINTAINER_MAKE_RULES = no ## used by maint.mk
+  FORCE_CHANGELOG_GENERATION = no
+endif
 
 # Check that we do not erreonously include in the tarball any file which
 # is not meant for distribution.
@@ -53,6 +61,67 @@ dist-hook: dist-hook-create-tarball-version
 .PHONY: dist-hook-create-tarball-version
 dist-hook-create-tarball-version:
 	echo '$(VERSION)' > $(distdir)/.tarball-version
+
+#
+# ChangeLog generation, from Git commit messages.
+#
+
+# Commits before this date shouldn't be put in the ChangeLog
+changelog_start_date = 2009-11-14
+
+# Use the commit dates of authors, not of commiters.
+gitlog_to_changelog_extra_options = --author-date
+
+dist-hook: dist-hook-generate-changelog
+.PHONY: dist-hook-generate-changelog
+dist-hook-generate-changelog:
+	$(AM_V_GEN)(set -u) >/dev/null 2>&1 && set -u; set -e; \
+	case '$(FORCE_CHANGELOG_GENERATION)' in \
+	  y|Y|yes|YES|true|1) force_chlog_gen=yes;; \
+	                   *) force_chlog_gen=no;; \
+	esac; \
+	if test ! -d '$(top_srcdir)/.git'; then \
+## probably the srcdir is from an extracted tarball
+	  if test x"$$force_chlog_gen" = x"yes"; then \
+## we must (re)generate the ChangeLog from git history, but no
+## git repository is available: give up
+	    echo "No .git directory found in top_srcdir \`$(top_srcdir)'" >&2; \
+	    echo "Cannot generate ChangeLog." >&2; \
+	    exit 1; \
+	  elif test ! -f '$(top_srcdir)/ChangeLog'; then \
+## no way to generate a new ChangeLog, nor to reuse the old one or an
+## hand-written one: give up
+	    echo "No .git directory and no ChangeLog file found in" >&2; \
+	    echo "top_srcdir \`$(top_srcdir)'" >&2; \
+	    echo "Cannot distribute ChangeLog." >&2; \
+	    exit 1; \
+	  else \
+## assume that either the existing ChangeLog is up-to-date, or that the
+## user properly updated it by hand
+	    cp -f '$(top_srcdir)/ChangeLog' $(distdir)/cl.tmp; \
+	  fi; \
+	else \
+## the srcdir is from a (maybe cloned) git repository, so we should be
+## able to generate the ChangeLog file from git history
+	  if test -n '$(gitlog_to_changelog_command)'; then \
+	    gitlog2chlog='$(gitlog_to_changelog_command)'; \
+	  else \
+	    gitlog2chlog='$(top_srcdir)/build-aux/gitlog-to-changelog'; \
+	  fi; \
+	  if test -n '$(changelog_start_date)'; then \
+	    changelog_start_date='$(changelog_start_date)'; \
+	  else \
+	    changelog_start_date='1970-01-01 UTC'; \
+	  fi; \
+	  GIT_DIR='$(abs_top_srcdir)/.git'; \
+	  GIT_WORK_TREE='$(abs_top_builddir)'; \
+	  export GIT_DIR GIT_WORK_TREE; \
+	  $$gitlog2chlog \
+	    --since="$$changelog_start_date" \
+	    $(gitlog_to_changelog_extra_options) >$(distdir)/cl.tmp; \
+	fi; \
+## if all went well, move the temporary ChangeLog to its final location
+	mv -f $(distdir)/cl.tmp $(distdir)/ChangeLog
 
 # This is defined here so that it can be extended in maint/*.mk, if needed.
 distcheck-hook:
@@ -81,12 +150,5 @@ maintainer-check-list-of-tests:
 	   (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$target) || fail=yes; \
 	 done; \
 	 test -z "$$fail"
-
-# $(ENABLE_MAINTAINER_MAKE_RULES): variable used by maint.mk
-if ENABLE_MAINTAINER_MAKE_RULES
-  ENABLE_MAINTAINER_MAKE_RULES = yes
-else
-  ENABLE_MAINTAINER_MAKE_RULES = no
-endif
 
 ## vim: ft=automake noet sw=4 ts=4
