M: tests/defs.in:   * added a way to bypass sanity checks (using the env var     `RAT4_BYPASS_TESTSUITE_SANITY_CHECKS ')   * now all names of used env vars have the form RAT4_* or __RAT4_*; e.g.      s/TESTING_GREP/RAT4_TESTING_GREP/   * in the trap fo EXIT: bugfix: s/$as_me/$me/   * some other minor bug fixings and improvements
M: tests/Makefile.am:
  * added defn to TEST_ENVIRONMENTS:
     + srcdir='$(srcdir)'

diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -8,7 +8,6 @@
 #
 
 (set -u) >/dev/null 2>&1 && set -u
-set -e
 
 # Shell initialization code, stolen from autoconf
 DUALCASE=1; export DUALCASE # for MKS sh
@@ -31,36 +30,53 @@ fi
 PACKAGE_VERSION='@PACKAGE_VERSION@'
 PACKAGE_NAME='@PACKAGE_NAME@'
 EXEEXT='@EXEEXT@'
-GREP=${TESTING_GREP-'@GREP@'}
-EGREP=${TESTING_EGREP-'@EGREP@'}
-FGREP=${TESTING_FGREP-'@FGREP@'}
-SED=${TESTING_SED-'@SED@'}
-SHELL=${TESTING_SHELL-'@SHELL@'}
+GREP=${RAT4_TESTING_GREP-'@GREP@'}
+EGREP=${RAT4_TESTING_EGREP-'@EGREP@'}
+FGREP=${RAT4_TESTING_FGREP-'@FGREP@'}
+SED=${RAT4_TESTING_SED-'@SED@'}
+SHELL=${RAT4_TESTING_SHELL-'@SHELL@'}
 
-# Be sure to run with the best shell found by configure
-if test x"${__RAT4_TESTSUITE_RERUN_WITH_CONFIG_SHELL__-}" = x"yes"; then
-    : # go ahead
-else
-    __RAT4_TESTSUITE_RERUN_WITH_CONFIG_SHELL__=yes
-    export __RAT4_TESTSUITE_RERUN_WITH_CONFIG_SHELL__
-    exec $SHELL "$0" ${1+"$@"}
-    exit 255
-fi
-unset __RAT4_TESTSUITE_RERUN_WITH_CONFIG_SHELL__
+case "${RAT4_TESTSUITE_FORCE_BIN_SH-}" in
+    y|Y|yes|Yes|YES|1)
+        # go ahead with the current shell
+        ;;
+    *)
+        # Be sure to run with the best shell found by configure
+        if test x"${__RAT4_TESTSUITE_RERUN_WITH_CONFIG_SHELL__-}" = x"yes"
+        then
+            : # go ahead
+        else
+            __RAT4_TESTSUITE_RERUN_WITH_CONFIG_SHELL__=yes
+            export __RAT4_TESTSUITE_RERUN_WITH_CONFIG_SHELL__
+            exec $SHELL "$0" ${1+"$@"}
+            exit 255
+        fi
+        ;;
+esac
+
+case "${RAT4_BYPASS_TESTSUITE_SANITY_CHECKS-}" in
+    y|Y|yes|Yes|YES|1) do_sanity_checks() { return 1; };;
+                    *) do_sanity_checks() { return 0; };;
+esac
+
+# Make errors fatal
+set -e
 
 # Used as a "fingerprint" to identify this file
 DEFS_ID='$Id$'
 
-# Ensure we are running from the right directory.
-test -f ./defs.sh || {
-   echo "defs.sh: not found in current directory" >&2
-   exit 1
-}
-$FGREP "$DEFS_ID" ./defs.sh >/dev/null || {
-   echo "defs.sh: does not contain expected \$Id\$ string:" >&2
-   echo "         $DEFS_ID" >&2
-   exit 1
-}
+if do_sanity_checks; then
+    # Ensure we are running from the right directory.
+    test -f ./defs.sh || {
+        echo "defs.sh: not found in current directory" >&2
+        exit 1
+    }
+    $FGREP "$DEFS_ID" ./defs.sh >/dev/null || {
+        echo "defs.sh: does not contain expected \$Id\$ string:" >&2
+        echo "         $DEFS_ID" >&2
+        exit 1
+    }
+fi
 
 test -n "${srcdir-}" || {
    # compute $srcdir.
@@ -68,18 +84,20 @@ test -n "${srcdir-}" || {
    test x"$srcdir" != x"$0" || srcdir=.
 }
 
-# Ensure $srcdir is set correctly.
-test -f "$srcdir/defs.in" || {
-   echo "$srcdir/defs.in: not found." >&2
-   echo "Please check \$srcdir." >&2
-   exit 1
-}
-$FGREP "$DEFS_ID" ./defs.sh >/dev/null || {
-   echo "$srcdir/defs.in: does not contain expected \$Id\$ string:" >&2
-   echo "                 $DEFS_ID" >&2
-   echo "Please check \$srcdir." >&2
-   exit 1
-}
+if do_sanity_checks; then
+    # Ensure $srcdir is set correctly.
+    test -f "$srcdir/defs.in" || {
+        echo "$srcdir/defs.in: not found." >&2
+        echo "Please check \$srcdir." >&2
+        exit 1
+    }
+    $FGREP "$DEFS_ID" "$srcdir/defs.in" >/dev/null || {
+        echo "$srcdir/defs.in: does not contain expected \$Id\$ string:">&2
+        echo "                 $DEFS_ID" >&2
+        echo "Please check \$srcdir." >&2
+        exit 1
+    }
+fi
 
 # name of running test
 me=`echo x/"$0" | $SED -e 's|.*/||' -e 's/\.test$//'`
@@ -96,14 +114,16 @@ curdir=`pwd`
 
 # Program to be tested
 RATFOR=${TESTED_RATFOR-"$curdir/ratfor${EXEEXT}"}
-test -f "$RATFOR" || {
-    echo "expected ratfor program to test not found: $RATFOR" >&2
-    exit 1
-}
-test -x "$RATFOR" || {
-    echo "expected ratfor program to test not executable: $RATFOR" >&2
-    exit 1
-}
+if do_sanity_checks; then
+    test -f "$RATFOR" || {
+        echo "expected ratfor program to test not found: $RATFOR" >&2
+        exit 1
+    }
+    test -x "$RATFOR" || {
+        echo "expected ratfor program to test not executable: $RATFOR" >&2
+        exit 1
+    }
+fi
 
 # We use a trap below for cleanup.  This requires us to go through
 # hoops to get the right exit status transported through the signal.
@@ -140,7 +160,7 @@ run() {
          *) _run_expected_exitcode=0;;
     esac
     _run_exitcode=0
-    case $* in
+    case $- in
         *x*) _run_reset_x='set -x';;
           *) _run_reset_x=':';;
     esac
@@ -171,8 +191,8 @@ if test x"$sh_errexit_works" = x"yes"; then
             0,|0,[Nn][Oo]) rm_rf ${testSubDir-};;
         esac
         test "$signal" != 0 &&
-          echo "$as_me: caught signal $signal"
-        echo "$as_me: exit $exit_status"
+          echo "$me: caught signal $signal"
+        echo "$me: exit $exit_status"
         exit $exit_status
   ' 0
   for signal in 1 2 13 15; do
