simplified exit trap in tests/defs.in
M: tests/defs.in:
  * simplified exit trap implementation: now it uses a global variable
    `$rat4_exit_default' instead of previously used the auxiliary file 
    `$testSubDir/exit.status'
       - subroutine `Exit()' modified accordingly
       - subroutine `cleanup_at_exit()' modified accordingly
       - removed definition `exitStatusFile = $testSubDir/exit.status'
       - added definition of default value for `$rat4_exit_default'
  * in `Exit()' and `cleanup_at_exit()': do not call `set +x' anymore,
    since its better if the exit trap is traced

diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -153,44 +153,38 @@ ws_normalize() { $SED -e "s/$ws1p/ /g" -e "s/^ *//" -e "s/ *$//"; }
 # We use a trap for cleanup.  This requires us to go through hoops to
 # get the right exit status transported through signals.  Also, more
 # hoops are required since there are shells (even some modern version
-# of Bash) which do not passes a "failure" exit status to the exit trap
-# when a syntax error is found.  Yay for them.
-# So use `Exit STATUS' instead of `exit STATUS' inside of the tests.
-
-# Will be defined later (once $testSubDir is defined):
-#  exitStatusFile=$testSubDir/exit.status
+# of Bash, e.g. bash-3.2 or bash-4.0) which do not passes a "failure"
+# exit status to the exit trap when a syntax error is found.  Sigh.
+# So use `Exit STATUS' instead of `exit STATUS' inside the tests.
 
 # Wrapper around exit, needed to pass the correct exit status to the
-# exit trap (see `cleanup_at_exit()') below
+# exit trap (see `cleanup_at_exit()') below.
 Exit() {
-    set +x
     set +e
-    echo "$1" >"$exitStatusFile"
-    (exit $1); exit $1;
+    rat4_exit_default=$1
+    (exit $1); exit $1
 }
 
 # Our exit trap: should deal with normal termination, signals,
 # untrapped failures and internal errors.
 cleanup_at_exit() {
-    set +x
+    rat4_exit_status=$?
     set +e
-    if test -s "${exitStatusFile-/dev/null}"; then
-        rat4_testcase_exit_status=`cat "$exitStatusFile"`
-        case $rat4_testcase_exit_status in
-            SIG*) rat4_testcase_signal=$rat4_testcase_exit_status
-                  rat4_testcase_exit_status=$E_HARD;;
-        esac
-        case $rat4_testcase_exit_status,${keep_testdirs-} in
-            0,|0,n|0,no|0,NO) rm_rf ${testSubDir-};;
-        esac
-        test -z "${rat4_testcase_signal-}" \
-          || echo "$me: caught signal $rat4_testcase_signal"
-    else
-        rat4_testcase_exit_status=$E_HARD
-        echo "$me: BADERR: internal error or untrapped failure" >&2
+    if test -n "${rat4_exit_signal-}"; then
+        echo "$me: caught signal $rat4_exit_signal"
+        rat4_exit_status=$E_HARD
+    elif test -z "${rat4_exit_default-}"; then
+        echo "$me: internal error or untrapped failure"
+        rat4_exit_status=$E_HARD
+    elif test x"$rat4_exit_default" != x"$rat4_exit_status"; then
+        echo "$me: exit status mismatch"
+        rat4_exit_status=$E_HARD
     fi
-    echo "$me: exit $rat4_testcase_exit_status"
-    exit $rat4_testcase_exit_status
+    case $rat4_exit_status,${keep_testdirs-} in
+        0,|0,n|0,no|0,NO) rm_rf ${testSubDir-};;
+    esac
+    echo "$me: exit $rat4_exit_status"
+    exit $rat4_exit_status
 }
 
 # Usage: testcase_PASS
@@ -319,19 +313,16 @@ run_F77() {
 
 # Setup cleanup traps.
 trap 'cleanup_at_exit' 0
-trap 'echo SIGHUP  >"$exitStatusFile" || :; Exit 1' 1
-trap 'echo SIGINT  >"$exitStatusFile" || :; Exit 1' 2
-trap 'echo SIGPIPE >"$exitStatusFile" || :; Exit 1' 13
-trap 'echo SIGTERM >"$exitStatusFile" || :; Exit 1' 15
+trap 'rat4_exit_signal=SIGHUP;  Exit $E_HARD' 1
+trap 'rat4_exit_signal=SIGINT;  Exit $E_HARD' 2
+trap 'rat4_exit_signal=SIGPIPE; Exit $E_HARD' 13
+trap 'rat4_exit_signal=SIGTERM; Exit $E_HARD' 15
 
 # Were the tests will run.
 rm_rf $me.dir
 mkdir $me.dir
 cd ./$me.dir
 testSubDir=`pwd` # absolute path
-
-# This is defined here and not before only because it needs $testSubDir.
-exitStatusFile="$testSubDir/exit.status"
 
 echo "=== Running test $0"
 
