Fixed potentially serious bug in tests/defs.in
M: tests/defs.in:
  * BUGFIX: sometimes, bash don't pass the a "failure" exit status to the
    exit trap if some syntax error is detected. This might cause false
    positive PASSes in testsuite, which is especially bad. Fixed this,
    by changeing the `Exit()' subroutine and the defintions of exit and
    signal traps
  * improved readability: exit trap code is now saved in the new
    `cleanup_at_exit()' subroutine
  * `$curdir' renamed as `$testrootdir'
  * variable `$testSubDir' now contains an absolute path
  * new variable `$exitStatusFile'
  * removed comment telling that "this file is havily based on automake's
    own tests/defs.in file": the two files are now quite different, and the
    previous comment does not hold anymore
  * removed use of `SH_ERREXIT_WORKS': it is no more needed

M: configure.ac:
  * removed call to `RAT4_CHECK_SH_ERREXIT_WORKS': no more needed

D: m4/rat4_check_sh_errexit_works.m4:
  * removed, no more needed

M: tests/README:
  * document new semantic of Exit() and of testcase scripts in general;
    in particular, explicitly state that `Exit()' must be called on
    either success or failure, otherwise the testcase will end in an
    "untrapped failure" a.k.a. "hard error"

M: tests/000sanity.test:
M: tests/devnull-input.test:
M: tests/empty-input.test:
M: tests/integers-many-bases.test:
   * accordingly to the new testcase semantic, call `Exit 1' on failure
     and `Exit 0' on success

diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -3,10 +3,6 @@
 # Common definitions and environments setting read (with the `source'
 # shell builtin) by all tests of ratfor.
 #
-# This file is heavily based on automake's own `tests/defs.in', so it
-# must be released under the GNU General Public License, version 2 or
-# later. For more info, see  <http://www.gnu.org/licenses/>.
-#
 
 # Shell initialization code, stolen from autoconf
 DUALCASE=1; export DUALCASE # for MKS sh
@@ -118,10 +114,10 @@ case "$srcdir" in
 esac
 
 # Absolute path of the directory where the test is run.
-curdir=`pwd`
+testrootdir=`pwd`
 
 # Program to be tested
-RATFOR=${RAT4_TESTUITE_RATFOR_EXECUTABLE-"$curdir/ratfor${EXEEXT}"}
+RATFOR=${RAT4_TESTUITE_RATFOR_EXECUTABLE-"$testrootdir/ratfor${EXEEXT}"}
 if do_sanity_checks; then
     test -f "$RATFOR" || {
         echo "expected ratfor program to test not found: $RATFOR" >&2
@@ -148,15 +144,47 @@ ws_strip() { $SED -e "s/^$ws0p//" -e "s/$ws0p$//"; }
 # and strip leading and trailing white spaces
 ws_normalize() { $SED -e "s/$ws1p/ /g" -e "s/^ *//" -e "s/ *$//"; }
 
-# We use a trap below for cleanup.  This requires us to go through
-# hoops to get the right exit status transported through the signal.
+# We use a trap for cleanup.  This requires us to go through hoops to
+# get the right exit status transported through the signal.  Also, more
+# hoops are required since there are shells (even some modern version
+# of Bash) which do not passes a "failure" exit status to the exit trap
+# when a syntax error is found.  Yay for them.
 # So use `Exit STATUS' instead of `exit STATUS' inside of the tests.
-# Turn off errexit here so that we don't trip the bug with OSF1/Tru64
-# sh inside this function.
+
+# Will be defined later (onoce testSubDir is defined):
+#  exitStatusFile=$testSubDir/exit.status
+
+# Wrapper around exit, needed to pass the correct exit status to the
+# exit trap (see `cleanup_at_exit()') below
 Exit() {
   set +e
+  echo "$1" >"$exitStatusFile"
   (exit $1)
   exit $1
+}
+
+# Our exit trap: should deal with normal termination, signals,
+# untrapped failures and internal errors.
+cleanup_at_exit() {
+    set +x
+    set +e
+    if test -s "${exitStatusFile-/dev/null}"; then
+        rat4_testcase_exit_status=`cat "$exitStatusFile"`
+        case $rat4_testcase_exit_status in
+            SIG*) rat4_testcase_signal=$rat4_testcase_exit_status
+                  rat4_testcase_exit_status=$E_HARD;;
+        esac
+        case $rat4_testcase_exit_status,${keep_testdirs-} in
+            0,|0,n|0,no|0,NO) rm_rf ${testSubDir-};;
+        esac
+        test -z "${rat4_testcase_signal-}" \
+          || echo "$me: caught signal $rat4_testcase_signal"
+    else
+        rat4_testcase_exit_status=$E_HARD
+        echo "$me: BADERR: internal error or untrapped failure" >&2
+    fi
+    echo "$me: exit $rat4_testcase_exit_status"
+    exit $rat4_testcase_exit_status
 }
 
 # Usage: testcase_SKIP [WHY]
@@ -214,8 +242,10 @@ NOT() {
 # Also, save standard output and standard error from the COMMAND
 # respectively in files `stdout' and `stderr'.
 run_CMD() {
-    # not to be diplayed even when `set -x' is active
-    { _run_prev_dollarminus=$-; set +x; } 2>/dev/null
+    # WARNING: Solaris /bin/sh does not like `{ a=1; } 2>/dev/null'
+    : restored '-x' flags
+    _run_prev_dollarminus=$-
+    set +x
     case ${_run_prev_dollarminus} in
         *x*) _run_reset_x='set -x';;
           *) _run_reset_x=':';;
@@ -237,10 +267,10 @@ run_CMD() {
     case "${_run_stdin}" in
       -)
         "${_run_cmd}" ${1+"$@"} >stdout 2>stderr || \
-            _run_exitcode=$?;;
+            _run_exitcode=$? ;;
       *)
         "${_run_cmd}" ${1+"$@"} <"${_run_stdin}" >stdout 2>stderr || \
-            _run_exitcode=$?;;
+            _run_exitcode=$? ;;
     esac
     echo "=== stderr" >&2
     cat stderr >&2
@@ -252,8 +282,8 @@ run_CMD() {
         *) _run_rc=1;;
     esac
     ${_run_reset_x}
-    # not to be diplayed even when `set -x' is active
-    { return ${_run_rc}; } 2>/dev/null
+    : restored '-x' flag
+    return ${_run_rc}
 }
 
 # Usage: run_RATFOR [-e STATUS] [-i INFILE] [ARGUMENTS..]
@@ -268,33 +298,21 @@ run_F77() {
     run_CMD "$RAT4_TESTSUITE_F77" ${1+"$@"}
 }
 
+# Setup cleanup traps
+trap 'cleanup_at_exit' 0
+trap 'echo SIGHUP  >"$exitStatusFile" || :; Exit 1' 1
+trap 'echo SIGINT  >"$exitStatusFile" || :; Exit 1' 2
+trap 'echo SIGPIPE >"$exitStatusFile" || :; Exit 1' 13
+trap 'echo SIGTERM >"$exitStatusFile" || :; Exit 1' 15
 
-# Setup cleanup trap
-sh_errexit_works='@SH_ERREXIT_WORKS@'
-if test x"$sh_errexit_works" = x"yes"; then
-    trap '
-        rat4_testcase_exit_status=$?
-        set +e
-        cd "$curdir"
-        case $rat4_testcase_exit_status,${keep_testdirs-} in
-            0,|0,[nN]|0,[Nn][Oo]) rm_rf ${testSubDir-};;
-        esac
-        test x"$rat4_testcase_signal" != x"0" && 
-          echo "$me: caught signal $rat4_testcase_signal"
-        echo "$me: exit $rat4_testcase_exit_status"
-        exit $rat4_testcase_exit_status
-  ' 0
-  for sig in 1 2 13 15; do
-    trap 'rat4_testcase_signal='$sig'; { Exit 1; }' $sig
-  done
-  unset sig
-fi
-rat4_testcase_signal=0
+# Were the tests will run
+rm_rf $me.dir
+mkdir $me.dir
+cd ./$me.dir
+testSubDir=`pwd` # absolute path
 
-testSubDir=$me.dir
-rm_rf $testSubDir
-mkdir $testSubDir
-cd ./$testSubDir
+# defined here since it needs $testSubDir
+exitStatusFile=$testSubDir/exit.status
 
 echo "=== Running test $0"
 
