M: configure.ac:   * added check for an option of diff that can produce better     human-readable output; thin in tun lead to...   * now AC_SUBST'd varable $(DIFF_U)   * version (in AC_INIT) bumped from 1.0c to 1.0d
M: tests/Makefile.am:
  * added a `check-list-of-tests' target checking that the list of
    tests in $(TEST) contains all the tests/*.test files
  * target `check-local' now depends from `check-list-of-tests'

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -4,12 +4,14 @@
 
 TESTS =	\
 000sanity.test \
-devnull-input.test \
-empty-input.test
+devnull-input.test
 
 EXTRA_DIST = $(TESTS)
 
 TESTS_ENVIRONMENT = srcdir='$(srcdir)'
+
+# might be updated later
+MOSTLYCLEANFILES = 
 
 # Each test case depends on defs.sh and ratfor
 check_SCRIPTS = ratfor defs.sh
@@ -24,6 +26,37 @@ $(top_builddir)/src/ratfor$(EXEEXT):
 	  && $(MAKE) $(AM_MAKEFLAGS) ratfor$(EXEEXT)
 
 TESTS_ENVIRONMENT += TESTED_RATFOR='$(abs_builddir)/ratfor$(EXEEXT)'
+
+# Check that the list of tests as given by $(TEST) is equal to the
+# list of all *.test scripts
+tmk = tests-in-makefile-list.tmp
+tfs = tests-in-makefile-list.tmp
+tdiffs = diff-in-tests-lists.tmp 
+check-list-of-tests:
+	@echo "****--------------------------------------------"
+	@echo "** Checking consistency of list of tests..."
+	@for t in $(TESTS); do \
+	    echo "$$t"; \
+	 done > $(tmk)
+	@(cd $(srcdir) && for t in *.tests; do \
+	    echo "$$t"; \
+	 done) > $(tfs)
+	@if $(DIFF_U) $(tmk) $(tfs) > $(tdiffs); then \
+	    : OK, no diffs; \
+	 else \
+	    echo "*** ERROR ***" >&2; \
+	    echo " List of tests in Makefile an on filesystem differ" >&2; \
+	    echo " + $(DIFF_U) in-makefile on-filesystem" >&2; \
+	    cat $(tdiffs) >&2; \
+		echo "****--------------------------------------------"; \
+	    exit 1; \
+	 fi;
+	@echo "** OK"
+	@echo "****--------------------------------------------"
+MOSTLYCLEANFILES += $(tmk) $(tfs) $(tdiffs)
+.PHONY: check-list-of-tests
+
+check-local: check-list-of-tests
 
 clean-local-testdirs:
 	find *.dir -type d '!' -perm -200 -exec chmod u+w {} ";"
